import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import FormSignUp from './formSignUp'
import FormValid from './FormValid'
export default function Home() {


  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Nasir</title>
          <meta name="description" content="Generated by Muhammad Nasir" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <FormValid /> */}
        <FormSignUp />
      </div>
    </>
  )
}

