import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Image from 'next/image'

const countriesData = [
  {
    name: "Germany",
    states: ["Duesseldorf", "Leinfelden-Echterdingen", "Eschborn"]
  },
  {
    name: "Pakistan",
    states: ["Lahore", "Islamabad", "Gujranwala", "Karachi"]
  },
  {
    name: "France",
    states: ["Auvergne", "Bretagne", "Corse", "Centre"]
  }
];


export default function Home() {
  const [registrationForm, setRegistrationFrom] = useState({
    firstName: "",
    lastName: "",
  })
  const [formInfo, setFromInfo] = useState([]);




  const inputChange = (event) => {
    const { name, value, type, checked } = event.target;
    setRegistrationFrom({ ...registrationForm, [name]: type === 'checkbox' ? checked : value, })
  }

  // Cascading dropdown

  const [{ country, city }, setData] = useState({
    country: "",
    city: ""
  });
  const countries = countriesData.map((country) => (
    <option key={country.name} value={country.name}>
      {country.name}
    </option>
  ));
  const states = countriesData.find(item => item.name === country)?.states.map((city) => (
    <option key={city} value={city}>
      {city}
    </option>
  ));
  function handleCountryChange(event) {
    setData(data => ({ city: '', country: event.target.value }));
  }
  function handleStateChange(event) {
    setData(data => ({ ...data, city: event.target.value }));
  }

  const [userinfo, setUserInfo] = useState({
    languages: [],
  });
  const handleChange = (e) => {
    // Destructuring
    const { value, checked } = e.target;
    const { languages } = userinfo;

    console.log(`${value} is ${checked}`);

    // Case 1 : The user checks the box
    if (checked) {
      setUserInfo({
        languages: [...languages, value],
      });
    }

    // Case 2 : The user unchecks the box
    else {
      setUserInfo({
        languages: languages.filter((e) => e !== value),
      });
    }
  };

  const [errors, setErrors] = useState({});



  const formSubmit = (e) => {
    e.preventDefault();
    const updateData = {
      ...userinfo,
      ...registrationForm,
      country,
      city,
    }
    setFromInfo([...formInfo, updateData])
    setRegistrationFrom({
      firstName: "",
      lastName: "",
    })
    setUserInfo({
      languages: [],
    })

    if (!errors.firstName) {
      setErrors("Must be Required")
    }
  }
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Nasir</title>
          <meta name="description" content="Generated by Muhammad Nasir" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <section className="text-gray-600 body-font">
          <div className="container px-5 py-2 mx-auto">
            <div className="lg:w-2/3 w-full mx-auto overflow-auto">
              <table className="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                  <tr>
                    <th className="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Image</th>
                    <th className="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">FirstName</th>
                    <th className="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">LastName</th>
                    <th className="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Country</th>
                    <th className="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">City</th>
                    <th className="px-1 py-1 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">languages</th>
                  </tr>
                </thead>
                <tbody>
                  {formInfo?.map((finfo, inde) => {
                    const { firstName, lastName, country, city, languages } = finfo;
                    return <tr key={inde}>
                      <td className="border-t-2 border-gray-200 px-4 py-1">
                        <Image width={100} height={100} className="block mx-auto w-10 h-10 rounded-full sm:mx-0 sm:shrink-0" src="/images/Nasir.jpg" alt="Woman's Face" />
                      </td>
                      <td className="border-t-2 border-gray-200 px-4 py-3">{firstName}</td>
                      <td className="border-t-2 border-gray-200 px-4 py-3">{lastName}</td>
                      <td className="border-t-2 border-gray-200 px-4 py-3">{country}</td>
                      <td className="border-t-2 border-gray-200 px-4 py-3">{city}</td>
                      {
                        languages.map((lang, ind) => <td key={ind} className="border-t-2 border-gray-200 ">{lang},</td>)
                      }
                    </tr>
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </section>
        <div className="hidden sm:block" aria-hidden="true">
          <div className="py-5">
            <div className="border-t border-gray-200" />
          </div>
        </div>
        <div className="mt-10 sm:mt-0 bg-gray-100 px-8 py-5 rounded-lg">
          <div className="md:grid md:grid-cols-3 md:gap-6">
            <div className="md:col-span-1">
              <div className="px-4 sm:px-0">
                <h3 className="text-lg font-medium leading-6 text-gray-900">Personal Information</h3>
                <p className="mt-1 text-sm text-gray-600">Use a permanent address where you can receive mail.</p>
              </div>
            </div>
            <div className="mt-5 md:col-span-2 md:mt-0">
              <form onSubmit={formSubmit}>
                <div className="overflow-hidden shadow sm:rounded-md">
                  <div className="bg-white px-4 py-5 sm:p-6">
                    <div className="grid grid-cols-6 gap-6">
                      <div className="col-span-6 sm:col-span-3">
                        <label htmlFor="firstName" className="block text-sm font-medium text-gray-700">
                          First name
                        </label>
                        <input
                          type="text"
                          name="firstName"
                          id="firstName"
                          value={registrationForm.firstName}
                          onChange={inputChange}
                          autoComplete="given-name"
                          className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm" />
                       <p> {errors.firstName}</p>
                      </div>
                      <div className="col-span-6 sm:col-span-3">
                        <label htmlFor="lastName" className="block text-sm font-medium text-gray-700">
                          Last name
                        </label>
                        <input
                          type="text"
                          name="lastName"
                          id="lastName"
                          value={registrationForm.lastName}
                          onChange={inputChange}
                          autoComplete="family-name"
                          className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm" />
                      </div>
                      <div className="col-span-6 sm:col-span-3">
                        <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                          Country
                        </label>
                        <select
                          id="country"
                          name="country"
                          value={country}
                          onChange={handleCountryChange}
                          autoComplete="country-name"
                          className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm">
                          <option value="" disabled>Select Country</option>
                          {countries}
                        </select>
                      </div>
                      <div className="col-span-6 sm:col-span-3">
                        <label htmlFor="country" className="block text-sm font-medium text-gray-700">
                          City
                        </label>
                        <select
                          id="city"
                          name="city"
                          value={city}
                          onChange={handleStateChange}
                          autoComplete="country-name"
                          className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm">
                          <option value="" disabled>Select City</option>
                          {states}
                        </select>
                      </div>
                      <div className="row">
                        <div className="col-md-6">
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="Javascript"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              Javascript
                            </label>
                          </div>
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="Python"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              Python
                            </label>
                          </div>
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="Java"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              Java
                            </label>
                          </div>
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="PHP"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              PHP
                            </label>
                          </div>
                        </div>
                        <div className="col-md-6">
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="C#"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              C#
                            </label>
                          </div>
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="C++"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              C++
                            </label>
                          </div>
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="C"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              C
                            </label>
                          </div>
                          <div className="form-check m-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              name="languages"
                              value="Typescript"
                              id="flexCheckDefault"
                              onChange={handleChange}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="flexCheckDefault"
                            >
                              Typescript
                            </label>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="bg-gray-50 px-4 py-3 text-right sm:px-6">
                    <button
                      type="submit"
                      className="inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                      Save
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

