import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CompleteFormWithOnePageWithoutProps from './CompleteFormWithOnePageWithoutProps'

import CheckBoxCascading from './checkBoxCascading'
import FormValid from './FormValid'
import SignUpPage from './Component/signUpPage'
import RegistrationPage from './Component/RegistrationPage'
import ForgotPassword from './Component/ForgotPassword'
export default function Home() {


  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Nasir</title>
          <meta name="description" content="Generated by Muhammad Nasir" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <FormValid /> */}
        {/* <CheckBoxCascading /> */}
        <ForgotPassword />
        <RegistrationPage />
        <SignUpPage />
        {/* <CompleteFormWithOnePageWithoutProps/> */}
      </div>
    </>
  )
}

